#!/usr/bin/env python3
"""
Fix Cell 3 in V5.1 notebook to add robust path detection with validation.
This prevents the 'ModuleNotFoundError: No module named bert_utils' error.
"""
import json
import sys

def fix_cell3():
    notebook_path = '01_ACOS_V5_1_FullExperiment_GPU_ROCM_CUDA_DriveSync.ipynb'
    
    # Read notebook
    with open(notebook_path, 'r', encoding='utf-8') as f:
        nb = json.load(f)
    
    # Find Cell 3 (the import cell)
    cell3_idx = None
    for i, cell in enumerate(nb['cells']):
        if cell['cell_type'] == 'code':
            source = ''.join(cell.get('source', []))
            if 'Sel 3: Import semua modul' in source and 'DETEKSI ROOT DIREKTORI PROYEK' in source:
                cell3_idx = i
                break
    
    if cell3_idx is None:
        print("❌ Cell 3 tidak ditemukan!")
        return False
    
    print(f"✓ Found Cell 3 at index {cell3_idx}")
    
    # New Cell 3 content with robust validation
    new_cell3_source = [
        "# Sel 3: Import semua modul & setup path dua-root (ROBUST V5.1 - Fixed)\n",
        "import os, sys, time, json, pickle, random, math, importlib, urllib.request\n",
        "from datetime import datetime\n",
        "from pathlib import Path\n",
        "\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import torch\n",
        "\n",
        "# ============================================================\n",
        "# 1. DETEKSI ROOT DIREKTORI PROYEK DENGAN VALIDASI LENGKAP\n",
        "# ============================================================\n",
        "\n",
        "ACOS_REPO_URL = \"https://github.com/haisyamalawwab/ACOS.git\"\n",
        "ACOS_ID_MODULES = [\n",
        "    \"taxonomy\", \"checkpoint\", \"cross_val\", \"experiment_runner\",\n",
        "    \"result_saver\", \"model_wrappers\", \"build_acos\", \"tokenize_data\", \"selftest\"\n",
        "]\n",
        "\n",
        "# Helper validation functions\n",
        "def _is_upstream(d):\n",
        "    \"\"\"Validasi Extract-Classify-ACOS lengkap (modeling.py + bert_utils/tokenization.py).\"\"\"\n",
        "    return os.path.isfile(os.path.join(d, 'modeling.py')) and os.path.isfile(os.path.join(d, 'bert_utils', 'tokenization.py'))\n",
        "\n",
        "def _validate_acos_id_complete(indo_path):\n",
        "    \"\"\"Validasi semua modul acos_id ada dan tidak kosong.\"\"\"\n",
        "    acos_id_dir = os.path.join(indo_path, 'acos_id')\n",
        "    if not os.path.isdir(acos_id_dir):\n",
        "        return False, ['acos_id directory missing']\n",
        "    missing = []\n",
        "    for m in ACOS_ID_MODULES:\n",
        "        fpath = os.path.join(acos_id_dir, f\"{m}.py\")\n",
        "        if not os.path.isfile(fpath) or os.path.getsize(fpath) == 0:\n",
        "            missing.append(f\"{m}.py\")\n",
        "    return len(missing) == 0, missing\n",
        "\n",
        "def _cari_base_project():\n",
        "    \"\"\"Cari base_project_dir: root yang memuat Extract-Classify-ACOS dan ACOS-IndoBERT LENGKAP.\"\"\"\n",
        "    kandidat = [\n",
        "        \"/shared-docker/ACOS\",\n",
        "        \"d:/laragon/www/ACOS-ASLI\",\n",
        "        \"D:/laragon/www/ACOS-ASLI\",\n",
        "        \"/content/drive/MyDrive/ACOS\",\n",
        "        \"/content/drive/MyDrive/ACOS-ASLI\",\n",
        "        str(Path.cwd().parent.parent),\n",
        "        str(Path.cwd().parent),\n",
        "        str(Path.cwd()),\n",
        "    ]\n",
        "    for _c in kandidat:\n",
        "        p = Path(_c)\n",
        "        if not p.is_dir():\n",
        "            continue\n",
        "        \n",
        "        extract = p / \"Extract-Classify-ACOS\"\n",
        "        indo = p / \"ACOS-IndoBERT\"\n",
        "        \n",
        "        # Validasi struktur dasar\n",
        "        if not (extract.exists() or indo.exists()):\n",
        "            continue\n",
        "        \n",
        "        # Validasi Extract-Classify-ACOS lengkap (bert_utils harus ada!)\n",
        "        has_valid_upstream = extract.exists() and _is_upstream(str(extract))\n",
        "        \n",
        "        # Validasi acos_id lengkap\n",
        "        has_valid_indo = False\n",
        "        if indo.exists():\n",
        "            is_complete, missing = _validate_acos_id_complete(str(indo))\n",
        "            has_valid_indo = is_complete\n",
        "            if not is_complete:\n",
        "                print(f\"⚠️  Skipping {_c}: acos_id incomplete (missing: {missing[:3]}...)\")\n",
        "        \n",
        "        # Butuh minimal salah satu lengkap\n",
        "        if has_valid_upstream or has_valid_indo:\n",
        "            if not has_valid_upstream:\n",
        "                print(f\"⚠️  {_c}: bert_utils missing, will try to clone Extract-Classify-ACOS later\")\n",
        "            return str(p.resolve())\n",
        "    \n",
        "    return None\n",
        "\n",
        "base_project_dir = _cari_base_project()\n",
        "if base_project_dir is None:\n",
        "    base_project_dir = os.path.abspath(\".\")\n",
        "    print(f\"⚠️  No valid project root found, using current directory: {base_project_dir}\")\n",
        "\n",
        "def _cari_indo_root():\n",
        "    \"\"\"Folder ACOS-IndoBERT dengan acos_id lengkap.\"\"\"\n",
        "    kandidat = [\n",
        "        os.path.join(base_project_dir, \"ACOS-IndoBERT\"),\n",
        "        os.path.abspath(\"ACOS-IndoBERT\"),\n",
        "        os.path.abspath(os.path.join(\"..\", \"ACOS-IndoBERT\")),\n",
        "        os.path.abspath(os.path.join(\"..\", \"..\", \"ACOS-IndoBERT\")),\n",
        "        os.path.abspath(\".\"),\n",
        "    ]\n",
        "    for _d in kandidat:\n",
        "        if os.path.isdir(os.path.join(_d, \"acos_id\")):\n",
        "            is_complete, missing = _validate_acos_id_complete(_d)\n",
        "            if is_complete:\n",
        "                return str(Path(_d).resolve())\n",
        "            else:\n",
        "                print(f\"⚠️  Skipping {_d}: incomplete acos_id (missing: {missing[:3]}...)\")\n",
        "    return None\n",
        "\n",
        "indo_root = _cari_indo_root()\n",
        "if indo_root is None:\n",
        "    _target = os.path.join(base_project_dir, \"ACOS-IndoBERT\")\n",
        "    print(f\"📥 ACOS-IndoBERT belum ada. Menyinkronkan ke {_target} ...\")\n",
        "    _tmp = \"/tmp/ACOS_clone_indo\"\n",
        "    os.system(f\"rm -rf {_tmp}\")\n",
        "    os.system(f\"git clone --depth 1 {ACOS_REPO_URL} {_tmp}\")\n",
        "    _src = os.path.join(_tmp, \"ACOS-IndoBERT\")\n",
        "    if os.path.isdir(os.path.join(_src, \"acos_id\")):\n",
        "        os.makedirs(_target, exist_ok=True)\n",
        "        os.system(f'cp -r \"{_src}/.\" \"{_target}/\"')\n",
        "        os.system(f\"rm -rf {_tmp}\")\n",
        "        indo_root = str(Path(_target).resolve())\n",
        "        print(\"✅ ACOS-IndoBERT tersinkron.\")\n",
        "    else:\n",
        "        indo_root = _target\n",
        "\n",
        "# ============================================================\n",
        "# 2. VALIDASI & SYNC MODUL ACOS_ID\n",
        "# ============================================================\n",
        "_acos_id_dir = os.path.join(indo_root, \"acos_id\")\n",
        "os.makedirs(_acos_id_dir, exist_ok=True)\n",
        "\n",
        "_missing = [\n",
        "    f\"{_m}.py\" for _m in ACOS_ID_MODULES\n",
        "    if not os.path.isfile(os.path.join(_acos_id_dir, f\"{_m}.py\"))\n",
        "    or os.path.getsize(os.path.join(_acos_id_dir, f\"{_m}.py\")) == 0\n",
        "]\n",
        "\n",
        "if _missing:\n",
        "    print(f\"📥 Modul acos_id belum lengkap ({len(_missing)} files). Menyinkronkan...\")\n",
        "    # 1. Coba git pull\n",
        "    if os.path.isdir(os.path.join(base_project_dir, \".git\")):\n",
        "        os.system(f\"git -C '{base_project_dir}' pull origin main\")\n",
        "    \n",
        "    # 2. Download missing files\n",
        "    _still_missing = [\n",
        "        _m for _m in _missing\n",
        "        if not os.path.isfile(os.path.join(_acos_id_dir, _m))\n",
        "        or os.path.getsize(os.path.join(_acos_id_dir, _m)) == 0\n",
        "    ]\n",
        "    for _fn in _still_missing:\n",
        "        _url = f\"https://raw.githubusercontent.com/haisyamalawwab/ACOS/main/ACOS-IndoBERT/acos_id/{_fn}\"\n",
        "        _target_file = os.path.join(_acos_id_dir, _fn)\n",
        "        try:\n",
        "            urllib.request.urlretrieve(_url, _target_file)\n",
        "            print(f\"   ✅ {_fn} berhasil diunduh dari GitHub\")\n",
        "        except Exception as _e:\n",
        "            print(f\"   ✗ Gagal mengunduh {_fn}: {_e}\")\n",
        "\n",
        "# ============================================================\n",
        "# 3. CARI & VALIDASI EXTRACT-CLASSIFY-ACOS (UPSTREAM ROOT)\n",
        "# ============================================================\n",
        "def _prepend_path(p):\n",
        "    \"\"\"Paksa p ke posisi terdepan sys.path.\"\"\"\n",
        "    try:\n",
        "        p_str = str(Path(p).resolve())\n",
        "    except Exception:\n",
        "        return None\n",
        "    if not os.path.isdir(p_str):\n",
        "        return None\n",
        "    while p_str in sys.path:\n",
        "        sys.path.remove(p_str)\n",
        "    sys.path.insert(0, p_str)\n",
        "    return p_str\n",
        "\n",
        "# Kandidat upstream dengan prioritas\n",
        "_up_candidates = [\n",
        "    os.path.join(base_project_dir, 'Extract-Classify-ACOS'),\n",
        "    os.path.join(os.path.dirname(indo_root), 'Extract-Classify-ACOS'),\n",
        "    '/content/Extract-Classify-ACOS',\n",
        "    '/content/ACOS/Extract-Classify-ACOS',\n",
        "    '/content/drive/MyDrive/ACOS/Extract-Classify-ACOS',\n",
        "    '/content/drive/MyDrive/ACOS-ASLI/Extract-Classify-ACOS',\n",
        "]\n",
        "\n",
        "upstream_root = None\n",
        "for _c in _up_candidates:\n",
        "    if _is_upstream(_c):\n",
        "        upstream_root = str(Path(_c).resolve())\n",
        "        print(f\"✓ Found valid upstream: {upstream_root}\")\n",
        "        break\n",
        "\n",
        "# Clone jika belum ada\n",
        "if upstream_root is None:\n",
        "    print(f\"📥 Extract-Classify-ACOS belum ada. Clone dari {ACOS_REPO_URL} ...\")\n",
        "    _tmpf = '/tmp/ACOS_full'\n",
        "    os.system(f\"rm -rf {_tmpf}\")\n",
        "    os.system(f\"git clone --depth 1 {ACOS_REPO_URL} {_tmpf}\")\n",
        "    _srcE = os.path.join(_tmpf, 'Extract-Classify-ACOS')\n",
        "    _dstE = os.path.join(base_project_dir if os.path.isdir(base_project_dir) else '/content', 'Extract-Classify-ACOS')\n",
        "    if _is_upstream(_srcE):\n",
        "        os.makedirs(os.path.dirname(_dstE), exist_ok=True)\n",
        "        os.system(f'cp -r \"{_srcE}\" \"{_dstE}\"')\n",
        "        print(f'  ✓ Copied: {_srcE} -> {_dstE}')\n",
        "        if _is_upstream(_dstE):\n",
        "            upstream_root = _dstE\n",
        "    os.system(f\"rm -rf {_tmpf}\")\n",
        "\n",
        "if upstream_root is None or not _is_upstream(upstream_root):\n",
        "    raise ModuleNotFoundError(\n",
        "        f\"❌ bert_utils tidak ditemukan!\\n\"\n",
        "        f\"upstream_root={upstream_root}\\n\"\n",
        "        f\"Dicoba: {_up_candidates}\\n\"\n",
        "        f\"Solusi: Upload folder Extract-Classify-ACOS atau git clone {ACOS_REPO_URL}\"\n",
        "    )\n",
        "\n",
        "# Setup sys.path\n",
        "_prepend_path(indo_root)\n",
        "_prepend_path(upstream_root)\n",
        "_prepend_path(base_project_dir)\n",
        "\n",
        "# Clear module cache\n",
        "for _m in list(sys.modules.keys()):\n",
        "    if _m == \"acos_id\" or _m.startswith(\"acos_id.\"):\n",
        "        del sys.modules[_m]\n",
        "\n",
        "print(\"\\n\" + \"=\"*65)\n",
        "print(\"✅ PATHS CONFIGURED SUCCESSFULLY\")\n",
        "print(\"=\"*65)\n",
        "print(f\"  base_project_dir : {base_project_dir}\")\n",
        "print(f\"  upstream_root    : {upstream_root}\")\n",
        "print(f\"  indo_root        : {indo_root}\")\n",
        "print(f\"  modeling.py      : {os.path.isfile(os.path.join(upstream_root, 'modeling.py'))}\")\n",
        "print(f\"  bert_utils/      : {os.path.isfile(os.path.join(upstream_root, 'bert_utils', 'tokenization.py'))}\")\n",
        "\n",
        "# ============================================================\n",
        "# 4. IMPORT MODUL LENGKAP\n",
        "# ============================================================\n",
        "print(f\"\\n{'='*60}\")\n",
        "print(\"Importing modules...\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "from bert_utils.tokenization import BertTokenizer\n",
        "print(\"  ✓ BertTokenizer\")\n",
        "\n",
        "from modeling import BertForQuadABSA, CategorySentiClassification\n",
        "print(\"  ✓ BertForQuadABSA, CategorySentiClassification\")\n",
        "\n",
        "acos_id = importlib.import_module(\"acos_id\")\n",
        "print(f\"  ✓ acos_id (v{getattr(acos_id, '__version__', '0.2.1')})\")\n",
        "\n",
        "acos_taxonomy = importlib.import_module(\"acos_id.taxonomy\")\n",
        "print(f\"  ✓ taxonomy ({len(getattr(acos_taxonomy, 'CATEGORIES', []))} categories)\")\n",
        "\n",
        "acos_ckpt = importlib.import_module(\"acos_id.checkpoint\")\n",
        "print(\"  ✓ checkpoint\")\n",
        "\n",
        "acos_cross_val = importlib.import_module(\"acos_id.cross_val\")\n",
        "build_with_ratio = acos_cross_val.build_with_ratio\n",
        "build_kfold_splits = acos_cross_val.build_kfold_splits\n",
        "ExperimentGrid = acos_cross_val.ExperimentGrid\n",
        "tokenize_all_splits = acos_cross_val.tokenize_all_splits\n",
        "print(\"  ✓ cross_val\")\n",
        "\n",
        "acos_experiment_runner = importlib.import_module(\"acos_id.experiment_runner\")\n",
        "prepare_all_data = acos_experiment_runner.prepare_all_data\n",
        "run_all_experiments = acos_experiment_runner.run_all_experiments\n",
        "aggregate_cv_results = acos_experiment_runner.aggregate_cv_results\n",
        "print(\"  ✓ experiment_runner\")\n",
        "\n",
        "acos_result_saver = importlib.import_module(\"acos_id.result_saver\")\n",
        "ResultSaver = acos_result_saver.ResultSaver\n",
        "merge_experiment_results = acos_result_saver.merge_experiment_results\n",
        "print(\"  ✓ result_saver\")\n",
        "\n",
        "model_wrappers = importlib.import_module(\"acos_id.model_wrappers\")\n",
        "print(\"  ✓ model_wrappers\")\n",
        "\n",
        "print(f\"\\n✅ ALL IMPORTS SUCCESSFUL!\")\n",
        "\n",
        "# ============================================================\n",
        "# 5. SEED GLOBAL & DIREKTORI OUTPUT\n",
        "# ============================================================\n",
        "random.seed(SEED)\n",
        "np.random.seed(SEED)\n",
        "torch.manual_seed(SEED)\n",
        "if torch.cuda.is_available():\n",
        "    torch.cuda.manual_seed_all(SEED)\n",
        "    if globals().get('ROCM_BENCHMARK', True):\n",
        "        torch.backends.cudnn.benchmark = True\n",
        "\n",
        "data_dir        = os.path.join(indo_root, \"data\", \"Apps-ACOS\")\n",
        "processed_dir   = os.path.join(data_dir, \"processed\")\n",
        "tokenized_base  = os.path.join(indo_root, \"tokenized_data\")\n",
        "results_base    = os.path.join(indo_root, \"results\")\n",
        "experiments_dir = os.path.join(results_base, \"experiments\")\n",
        "bert_cache_dir  = os.path.join(indo_root, \"backbones\", \"indobert_base_p1\")\n",
        "\n",
        "os.makedirs(experiments_dir, exist_ok=True)\n",
        "\n",
        "print(f\"\\nDirectory paths configured:\")\n",
        "print(f\"  data_dir        : {data_dir}\")\n",
        "print(f\"  tokenized_base  : {tokenized_base}\")\n",
        "print(f\"  experiments_dir : {experiments_dir}\")\n",
        "\n",
        "# --- V5.1: Drive sync helper ---\n",
        "import shutil\n",
        "GDRIVE_MOUNTED = os.path.exists('/content/drive/MyDrive')\n",
        "GDRIVE_BACKUP_DIR = None\n",
        "if GDRIVE_MOUNTED:\n",
        "    GDRIVE_BACKUP_DIR = os.path.join('/content/drive/MyDrive', globals().get('GDRIVE_BACKUP_SUBDIR', 'ACOS_V51_BACKUP'))\n",
        "    os.makedirs(GDRIVE_BACKUP_DIR, exist_ok=True)\n",
        "    print(f'\\n✓ Drive mounted: {GDRIVE_BACKUP_DIR}')\n",
        "else:\n",
        "    print('\\n✓ Running locally (no Drive sync)')\n",
        "\n",
        "def sync_to_gdrive(source_path, target_subpath=''):\n",
        "    \"\"\"Mirror file/folder ke Google Drive bila mounted.\"\"\"\n",
        "    if not globals().get('DRIVE_SYNC', True) or not GDRIVE_MOUNTED or not GDRIVE_BACKUP_DIR:\n",
        "        return None\n",
        "    try:\n",
        "        dest_dir = os.path.join(GDRIVE_BACKUP_DIR, target_subpath) if target_subpath else GDRIVE_BACKUP_DIR\n",
        "        os.makedirs(dest_dir, exist_ok=True)\n",
        "        if os.path.isdir(source_path):\n",
        "            dest = os.path.join(dest_dir, os.path.basename(source_path.rstrip('/')))\n",
        "            if os.path.exists(dest):\n",
        "                shutil.rmtree(dest)\n",
        "            shutil.copytree(source_path, dest)\n",
        "            return dest\n",
        "        else:\n",
        "            shutil.copy2(source_path, dest_dir)\n",
        "            return os.path.join(dest_dir, os.path.basename(source_path))\n",
        "    except Exception as e:\n",
        "        print(f'⚠️  sync_to_gdrive gagal: {e}')\n",
        "        return None\n",
        "\n",
        "print(f\"\\n✅ Setup complete! Ready for training.\")\n"
    ]
    
    # Update cell
    nb['cells'][cell3_idx]['source'] = new_cell3_source
    nb['cells'][cell3_idx]['outputs'] = []  # Clear old outputs
    nb['cells'][cell3_idx]['execution_count'] = None  # Reset execution count
    
    # Write back
    with open(notebook_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, ensure_ascii=False, indent=1)
    
    print(f"\n✅ Cell 3 updated successfully in {notebook_path}")
    print(f"   New cell has {len(new_cell3_source)} lines with robust validation")
    return True

if __name__ == '__main__':
    try:
        success = fix_cell3()
        sys.exit(0 if success else 1)
    except Exception as e:
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
